image: node:18-alpine3.14

stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
    url: https://graphql-core-schema.netlify.app/
  script:
    - apk add --no-cache zip curl
    - npm install netlify-cli --save-dev --global
    - npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --trigger
